logging:
  level:
   org.springframework.data.r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/timetable
    username: ${DB_POSTGRES_USER}
    password: ${DB_POSTGRES_PASSWORD}

  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/static/
    suffix: .html

  flyway:
    url: jdbc:postgresql://localhost:5432/timetable
    user: ${DB_POSTGRES_USER}
    password: ${DB_POSTGRES_PASSWORD}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400